[package]
name = "server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
noughts-and-crosses-core = { path = "../core" }

bincode = { workspace = true }
futures-util = { workspace = true }
rand = { workspace = true }
worker = { workspace = true }
